# Generated by Django 2.0.1 on 2018-05-22 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018')], default=2015)),
                ('total_cows', models.SmallIntegerField(default=0)),
                ('aged_cows', models.SmallIntegerField(default=0)),
                ('pregnant_cows', models.SmallIntegerField(default=0)),
                ('ill_cows', models.SmallIntegerField(default=0)),
                ('injured_cows', models.SmallIntegerField(default=0)),
                ('gallons_milk', models.SmallIntegerField(default=0)),
                ('link', models.URLField(max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018')], default=2015)),
                ('month', models.SmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('total_cows', models.SmallIntegerField(default=0)),
                ('aged_cows', models.SmallIntegerField(default=0)),
                ('pregnant_cows', models.SmallIntegerField(default=0)),
                ('ill_cows', models.SmallIntegerField(default=0)),
                ('injured_cows', models.SmallIntegerField(default=0)),
                ('gallons_milk', models.SmallIntegerField(default=0)),
                ('link', models.URLField(max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
