# Generated by Django 2.0.1 on 2018-04-12 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=2015)),
                ('total_cows', models.SmallIntegerField(default=0)),
                ('aged_cows', models.SmallIntegerField(default=0)),
                ('pregnant_cows', models.SmallIntegerField(default=0)),
                ('ill_cows', models.SmallIntegerField(default=0)),
                ('injured_cows', models.SmallIntegerField(default=0)),
                ('gallons_milk', models.SmallIntegerField(default=0)),
                ('link', models.URLField(max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=2015)),
                ('month', models.SmallIntegerField(default=1)),
                ('total_cows', models.SmallIntegerField(default=0)),
                ('aged_cows', models.SmallIntegerField(default=0)),
                ('pregnant_cows', models.SmallIntegerField(default=0)),
                ('ill_cows', models.SmallIntegerField(default=0)),
                ('injured_cows', models.SmallIntegerField(default=0)),
                ('gallons_milk', models.SmallIntegerField(default=0)),
                ('link', models.URLField(max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
