# Generated by Django 2.0.1 on 2018-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annual',
            name='year',
            field=models.SmallIntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018')], default=2015),
        ),
    ]
