# Generated by Django 2.0.1 on 2018-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_auto_20180427_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='month',
            field=models.SmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='year',
            field=models.SmallIntegerField(choices=[(2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018')], default=2015),
        ),
    ]
