#!/bin/bash

function clean_up() {
    rm ./db.sqlite3
    rm ./assets/migrations/0001_initial.py
    rm ./summary/migrations/0001_initial.py
}

function start_fresh() {
    python manage.py check
    python manage.py makemigrations
    python manage.py migrate
}

function load_dependencies() {
    ./tools/create_user.py -f old -l mcdonald -e farmer@dairyfarm.org -u farmer -p milk
    ./tools/create_user.py -f mister -l greenjeans -e farmhand@dairyfarm.org -u farmhand -p butter
    ./tools/create_user.py -f doctor -l fixmeup -e vet@dairyfarm.org -u vet -p cheese
    ./tools/create_user.py -f kama -l kamahameka -e kama@dairyfarm.org -u kama -p kama -s
    ./tools/create_user.py -f foster -l farms -e foster_farms@ff.org -u foster -p farms
    ./tools/create_user.py -f berkeley -l farms -e berkeley_farms@bf.org -u berkeley -p farms
    ./tools/create_user.py -f mcclelland -l dairy -e mcclelland_dairy@md.org -u mcclelland -p dairy
    ./tools/create_user.py -f clauss -l dairy -e clauss_dairy_farms@cdf.org -u clauss -p dairy
    ./tools/create_user.py -f dairy -l farmers -e dairy_farmers@dfoa.org -u dairy -p farmers
    ./tools/load_references.py
}

function purchase_cows() {
    user=$1
    dt=$2
    quantity=$3
    for breed in holstein jersey guernsey ayrshire brown_swiss milking_shorthorn dutch_belted
    do
        ./tools/purchase_herd.py -b $breed -d "$dt" -q $quantity -u $user
    done
}

function seed_pastures() {
    season=$1
    user=$2
    year=$3
    if [ $user == "foster" ]; then
        ./tools/seed_pastures.py -c alfalfa -g bermuda -l clover -p North -s $season -u $user -y $year
        ./tools/seed_pastures.py -c barley -g bluegrass -l cowpeas -p West -s $season -u $user -y $year
        ./tools/seed_pastures.py -c oat -g brome -l lespedeza -p South -s $season -u $user -y $year
        ./tools/seed_pastures.py -c rye -g fescue -l soybean -p East -s $season -u $user -y $year
        ./tools/seed_pastures.py -c wheat -g orchardgrass -l trefoil -p 'Central North' -s $season -u $user -y $year
        ./tools/seed_pastures.py -c alfalfa -g 'reed canary grass' -l vetch -p 'Central West' -s $season -u $user -y $year
        ./tools/seed_pastures.py -c barley -g ryegrass -l clover -p 'Central South' -s $season -u $user -y $year
        ./tools/seed_pastures.py -c oat -g sudangrass -l cowpeas -p 'Central East' -s $season -u $user -y $year
        ./tools/seed_pastures.py -c rye -g timothy -l lespedeza -p 'North West' -s $season -u $user -y $year
        ./tools/seed_pastures.py -c wheat -g bermuda -l soybean -p 'North East' -s $season -u $user -y $year
    elif [ $user == "berkeley" ]; then
        ./tools/seed_pastures.py -c alfalfa -g bermuda -l clover -p Lot_1 -s $season -u $user -y $year
        ./tools/seed_pastures.py -c barley -g bluegrass -l cowpeas -p Lot_2  -s $season -u $user -y $year
        ./tools/seed_pastures.py -c oat -g brome -l lespedeza -p Lot_3 -s $season -u $user -y $year
        ./tools/seed_pastures.py -c rye -g fescue -l soybean -p Lot_4 -s $season -u $user -y $year
        ./tools/seed_pastures.py -c wheat -g orchardgrass -l trefoil -p Lot_5 -s $season -u $user -y $year
        ./tools/seed_pastures.py -c alfalfa -g 'reed canary grass' -l vetch -p Lot_6 -s $season -u $user -y $year
        ./tools/seed_pastures.py -c barley -g ryegrass -l clover -p Lot_7 -s $season -u $user -y $year
        ./tools/seed_pastures.py -c oat -g sudangrass -l cowpeas -p Lot_8 -s $season -u $user -y $year
    fi
}

function fallow_pastures() {
    user=$1
    if [ $user == "foster" ]; then
        ./tools/assign_fallow_pastures.py -p "South West" -u $user
        ./tools/assign_fallow_pastures.py -p "South East" -u $user
        ./tools/assign_fallow_pastures.py -p "Pen" -u $user
    elif [ $user == "berkeley" ]; then
        ./tools/assign_fallow_pastures.py -p Lot_9 -u $user
    fi
}

function generate_daily_activity() {
    user=$1
    dt=$2
    for color in black_white red_white
    do
        ./tools/daily_herd_activity.py -b holstein -c $color -d "$dt" -u $user
    done
    for color in brown tawny
    do
        ./tools/daily_herd_activity.py -b jersey -c $color -d "$dt" -u $user
    done
    for breed in guernsey ayrshire
    do
        ./tools/daily_herd_activity.py -b $breed -c golden_white -d "$dt" -u $user
    done
    for color in brown gray
    do
        ./tools/daily_herd_activity.py -b brown_swiss -c $color -d "$dt" -u $user
    done
    for color in red white roan red_white
    do
        ./tools/daily_herd_activity.py -b milking_shorthorn -c $color -d "$dt" -u $user
    done
    ./tools/daily_herd_activity.py -b dutch_belted -c black_white -d "$dt" -u $user
}

function generate_monthly_activity() {
    user=$1
    year=$2
    month=$3
    if [ $month -eq 2 ]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-0$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
        do
            generate_daily_activity $1 $year-0$month-$day
        done
    elif [[ $month -eq 4 || $month -eq 6 || $month -eq 9 ]]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-0$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
        do
            generate_daily_activity $1 $year-0$month-$day
        done
    elif [ $month -eq 11 ]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
        do
            generate_daily_activity $1 $year-$month-$day
        done
    elif [[ $month -eq 1 || $month -eq 3 || $month -eq 5 || $month -eq 7 || $month -eq 8 ]]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-0$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
        do
            generate_daily_activity $1 $year-0$month-$day
        done
    elif [[ $month -eq 10 || $month -eq 12 ]]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
        do
            generate_daily_activity $1 $year-$month-$day
        done
    fi
}

function preserve_reference_data() {
    ./tools/create_fixtures.py
}

function reporting() {
    duration=$1
    user=$2
    if [ $# -eq 4 ]; then
        year=$3
        month=$4
        echo reporting $duration $user $year $month
        ./tools/reporting.py --duration $duration --username $user --year $year --month $month
    elif [ $# -eq 3 ]; then
        year=$3
        echo reporting $duration $user $year
        ./tools/reporting.py --duration $duration --username $user --year $year
    fi
}

function test() {
    python manage.py test -v 2 assets.tests.test_models
    python manage.py test -v 2 assets.tests.test_serializers
    python manage.py test -v 2 assets.tests.test_api_views
    python manage.py test -v 2 assets.tests.test_urls
    python manage.py test -v 2 summary.tests.test_models
    python manage.py test -v 2 summary.tests.test_serializers
    python manage.py test -v 2 summary.tests.test_api_views
    python manage.py test -v 2 summary.tests.test_urls
}
