#!/bin/bash

function clean_up() {
    rm ./db.sqlite3
    rm ./assets/migrations/0001_initial.py
}

function start_fresh() {
    python manage.py check
    python manage.py makemigrations
    python manage.py migrate
}

function load_dependencies() {
    ./tools/create_user.py -f old -l mcdonald -e farmer@dairyfarm.org -u farmer -p milk
    ./tools/create_user.py -f mister -l greenjeans -e farmhand@dairyfarm.org -u farmhand -p butter
    ./tools/create_user.py -f doctor -l fixmeup -e vet@dairyfarm.org -u vet -p cheese
    ./tools/load_references.py
}

function purchase_cows() {
    user=$1
    dt=$2
    quantity=$3
    for color in black_white red_white
    do
        ./tools/purchase_herd.py -b holstein -c $color -d "$dt" -q $quantity -u $user
    done
    for color in brown tawny
    do
        ./tools/purchase_herd.py -b jersey -c $color -d "$dt" -q $quantity -u $user
    done
    ./tools/purchase_herd.py -b guernsey -c golden_white -d "$dt" -q $quantity -u $user
    ./tools/purchase_herd.py -b ayrshire -c golden_white -d "$dt" -q $quantity -u $user
    for color in brown gray
    do
        ./tools/purchase_herd.py -b brown_swiss -c $color -d "$dt" -q $quantity -u $user
    done
    for color in red white roan red_white
    do
        ./tools/purchase_herd.py -b milking_shorthorn -c $color -d "$dt" -q $quantity -u $user
    done
    ./tools/purchase_herd.py -b dutch_belted -c black_white -d "$dt" -q $quantity -u $user
}

function seed_pastures() {
    season=$1
    user=$2
    year=$3
    ./tools/seed_pastures.py -c alfalfa -g bermuda -l clover -r North -s $season -u $user -y $year
    ./tools/seed_pastures.py -c barley -g bluegrass -l cowpeas -r West -s $season -u $user -y $year
    ./tools/seed_pastures.py -c oat -g brome -l lespedeza -r South -s $season -u $user -y $year
    ./tools/seed_pastures.py -c rye -g fescue -l soybean -r East -s $season -u $user -y $year
    ./tools/seed_pastures.py -c wheat -g orchardgrass -l trefoil -r 'Central North' -s $season -u $user -y $year
    ./tools/seed_pastures.py -c alfalfa -g 'reed canary grass' -l vetch -r 'Central West' -s $season -u $user -y $year
    ./tools/seed_pastures.py -c barley -g ryegrass -l clover -r 'Central South' -s $season -u $user -y $year
    ./tools/seed_pastures.py -c oat -g sudangrass -l cowpeas -r 'Central East' -s $season -u $user -y $year
    ./tools/seed_pastures.py -c rye -g timothy -l lespedeza -r 'North West' -s $season -u $user -y $year
    ./tools/seed_pastures.py -c wheat -g bermuda -l soybean -r 'North East' -s $season -u $user -y $year
    ./tools/seed_pastures.py -c alfalfa -g bluegrass -l trefoil -r 'South West' -s $season -u $user -y $year
    ./tools/seed_pastures.py -c barley -g brome -l vetch -r 'South East' -s $season -u $user -y $year
    ./tools/seed_pastures.py -c oat -g brome -l lespedeza -r Pen -s $season -u $user -y $year
}

function fallow_pastures() {
    season=$1
    user=$2
    year=$3
    ./tools/assign_fallow_pastures.py -r "South West" -s $season -u $user -y $year
    ./tools/assign_fallow_pastures.py -r "South East" -s $season -u $user -y $year
    ./tools/assign_fallow_pastures.py -r "Pen" -s $season -u $user -y $year
}

function generate_daily_activity() {
    user=$1
    dt=$2
    for color in black_white red_white
    do
        ./tools/daily_herd_activity.py -b holstein -c $color -d "$dt" -u $user
    done
    for color in brown tawny
    do
        ./tools/daily_herd_activity.py -b jersey -c $color -d "$dt" -u $user
    done
    for breed in guernsey ayrshire
    do
        ./tools/daily_herd_activity.py -b $breed -c golden_white -d "$dt" -u $user
    done
    for color in brown gray
    do
        ./tools/daily_herd_activity.py -b brown_swiss -c $color -d "$dt" -u $user
    done
    for color in red white roan red_white
    do
        ./tools/daily_herd_activity.py -b milking_shorthorn -c $color -d "$dt" -u $user
    done
    ./tools/daily_herd_activity.py -b dutch_belted -c black_white -d "$dt" -u $user
}

function generate_monthly_activity() {
    user=$1
    year=$2
    month=$3
    if [ $month -eq 2 ]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-0$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
        do
            generate_daily_activity $1 $year-0$month-$day
        done
    elif [[ $month -eq 4 || $month -eq 6 || $month -eq 9 ]]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-0$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
        do
            generate_daily_activity $1 $year-0$month-$day
        done
    elif [ $month -eq 11 ]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
        do
            generate_daily_activity $1 $year-$month-$day
        done
    elif [[ $month -eq 1 || $month -eq 3 || $month -eq 5 || $month -eq 7 || $month -eq 8 ]]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-0$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
        do
            generate_daily_activity $1 $year-0$month-$day
        done
    elif [[ $month -eq 10 || $month -eq 12 ]]; then
        for day in 1 2 3 4 5 6 7 8 9
        do
            generate_daily_activity $1 $year-$month-0$day
        done
        for day in 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
        do
            generate_daily_activity $1 $year-$month-$day
        done
    fi
}

function preserve_reference_data() {
    ./tools/create_fixtures.py
}

function test() {
    python manage.py test -v 2
}
