#!/bin/bash

export STIME=`date`
# CLEAN UP
rm ./db.sqlite3
rm ./assets/migrations/0001_initial.py

# START FRESH
python manage.py check
python manage.py makemigrations
python manage.py migrate

# LOAD DEPENDENCIES
./tools/create_user.py -f old -l mcdonald -e farmer@dairyfarm.org -u farmer -p milk
./tools/create_user.py -f mister -l greenjeans -e farmhand@dairyfarm.org -u farmhand -p butter
./tools/create_user.py -f doctor -l fixmeup -e vet@dairyfarm.org -u vet -p cheese
./tools/load_references.py

# PURCHASE COWS
user="farmhand"
dt="2014-12-31"
for color in black_white red_white
do
    ./tools/purchase_herd.py -b holstein -c $color -d "$dt" -q 10 -u $user
done
for color in brown tawny
do
    ./tools/purchase_herd.py -b jersey -c $color -d "$dt" -q 10 -u $user
done
./tools/purchase_herd.py -b guernsey -c golden_white -d "$dt" -q 10 -u $user
./tools/purchase_herd.py -b ayrshire -c golden_white -d "$dt" -q 10 -u $user
for color in brown gray
do
    ./tools/purchase_herd.py -b brown_swiss -c $color -d "$dt" -q 10 -u $user
done
for color in red white roan red_white
do
    ./tools/purchase_herd.py -b milking_shorthorn -c $color -d "$dt" -q 10 -u $user
done
./tools/purchase_herd.py -b dutch_belted -c black_white -d "$dt" -q 10 -u $user

# SEED PASTURES
./tools/seed_pastures.py -c alfalfa -g bermuda -l clover -s Spring -r North -u farmhand
./tools/seed_pastures.py -c barley -g bluegrass -l cowpeas -s Spring -r West -u farmhand
./tools/seed_pastures.py -c oat -g brome -l lespedeza -s Spring -r South -u farmhand
./tools/seed_pastures.py -c rye -g fescue -l soybean -s Spring -r East -u farmhand
./tools/seed_pastures.py -c wheat -g orchardgrass -l trefoil -s Spring -r 'Central North' -u farmhand
./tools/seed_pastures.py -c alfalfa -g 'reed canary grass' -l vetch -s Spring -r 'Central West' -u farmhand
./tools/seed_pastures.py -c barley -g ryegrass -l clover -s Spring -r 'Central South' -u farmhand
./tools/seed_pastures.py -c oat -g sudangrass -l cowpeas -s Spring -r 'Central East' -u farmhand
./tools/seed_pastures.py -c rye -g timothy -l lespedeza -s Spring -r 'North West' -u farmhand
./tools/seed_pastures.py -c wheat -g bermuda -l soybean -s Spring -r 'North East' -u farmhand
./tools/seed_pastures.py -c alfalfa -g bluegrass -l trefoil -s Spring -r 'South West' -u farmhand
./tools/seed_pastures.py -c barley -g brome -l vetch -s Spring -r 'South East' -u farmhand
./tools/seed_pastures.py -c oat -g brome -l lespedeza -s Spring -r Pen -u farmhand

# ASSIGN FALLOW PASTURES 
./tools/assign_fallow_pastures.py -s Spring -r 'South West' -u farmhand
./tools/assign_fallow_pastures.py -s Spring -r 'South East' -u farmhand
./tools/assign_fallow_pastures.py -s Spring -r 'Pen' -u farmhand

# GENERATE WEEKLY ACTIVITY
user="vet"
#for day in 1 2 3 4 5 6 7
for day in 1
do
    dt="2015-01-0$day"
    ./tools/daily_herd_activity.py -b holstein -c black_white -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b holstein -c red_white -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b jersey -c brown -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b jersey -c tawny -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b guernsey -c golden_white -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b ayrshire -c golden_white -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b brown_swiss -c brown -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b brown_swiss -c gray -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b milking_shorthorn -c red -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b milking_shorthorn -c white -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b milking_shorthorn -c roan -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b milking_shorthorn -c red_white -d "$dt" -u $user
    ./tools/daily_herd_activity.py -b dutch_belted -c black_white -d "$dt" -u $user
done

# PRESERVE REFERENCE DATA AS FIXTURES
./tools/create_fixtures.py

# TEST
python manage.py test -v 2

#export ETIME=`date`
echo started $STIME
echo finished $ETIME
