#!/bin/bash

. ./tools/functions --source-only

export STIME=`date`

# main
clean_up
start_fresh
load_dependencies
# 2015
purchase_cows foster 2014-12-31 10
purchase_cows berkeley 2014-12-31 8
seed_pastures Spring foster 2015
seed_pastures Spring berkeley 2015
fallow_pastures foster 2015
fallow_pastures berkeley 2015
generate_daily_activity vet 2015-01-01
generate_daily_activity vet 2015-02-01
generate_daily_activity vet 2015-03-01
reporting monthly foster 2015 01
reporting monthly foster 2015 02
reporting monthly foster 2015 03
reporting monthly berkeley 2015 01
reporting monthly berkeley 2015 02
reporting monthly berkeley 2015 03
reporting annual foster 2015
reporting annual berkeley 2015
preserve_reference_data
test
export ETIME=`date`
echo started $STIME
echo finished $ETIME
