from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from assets.api_views import ActionListView, AgeListView, BreedListView
from assets.api_views import CerealListView, ClientListView, ColorListView
from assets.api_views import GrassListView, IllnessListView, InjuryListView
from assets.api_views import LegumeListView, SeasonListView, StatusListView
from assets.api_views import TreatmentListView, UserListView, VaccineListView
from assets.api_views import CowDetailView, CowListView
from assets.api_views import CowListByMonthView, CowListByYearView
from assets.api_views import EventDetailView, EventListView
from assets.api_views import ExerciseDetailView, ExerciseListView
from assets.api_views import HealthRecordDetailView, HealthRecordListView
from assets.api_views import HealthRecordListByMonthView
from assets.api_views import HealthRecordIllCowsSummaryView
from assets.api_views import MilkDetailView, MilkListView
from assets.api_views import MilkListByMonthView, MilkSummaryByMonthView
from assets.api_views import PastureDetailView, PastureListView
from assets.api_views import SeedDetailView, SeedListView
from assets.views import IndexView

app_name = 'assets'
urlpatterns = [
    url(r'^$',
        IndexView.as_view(),
        name='asset-index'),
    url(r'^api/actions/$',
        ActionListView.as_view(),
        name='action-list'),
    url(r'^api/ages/$',
        AgeListView.as_view(),
        name='age-list'),
    url(r'^api/breeds/$',
        BreedListView.as_view(),
        name='breed-list'),
    url(r'^api/cereals/$',
        CerealListView.as_view(),
        name='cereal-list'),
    url(r'^api/clients/$',
        ClientListView.as_view(),
        name='client-list'),
    url(r'^api/colors/$',
        ColorListView.as_view(),
        name='color-list'),
    url(r'^api/grasses/$',
        GrassListView.as_view(),
        name='grass-list'),
    url(r'^api/illnesses/$',
        IllnessListView.as_view(),
        name='illness-list'),
    url(r'^api/injuries/$',
        InjuryListView.as_view(),
        name='injury-list'),
    url(r'^api/legumes/$',
        LegumeListView.as_view(),
        name='legume-list'),
    url(r'^api/seasons/$',
        SeasonListView.as_view(),
        name='season-list'),
    url(r'^api/statuses/$',
        StatusListView.as_view(),
        name='status-list'),
    url(r'^api/treatments/$',
        TreatmentListView.as_view(),
        name='treatment-list'),
    url(r'^api/users/$',
        UserListView.as_view(),
        name='user-list'),
    url(r'^api/vaccines/$',
        VaccineListView.as_view(),
        name='vaccine-list'),
    url(r'^api/cows/$',
        CowListView.as_view(),
        name='cow-list'),
    url(r'^api/cows/year/(?P<year>[0-9]{4})/month/(?P<month>[0-9]{2})/$',
        CowListByMonthView.as_view(),
        name='cow-list-month'),
    url(r'^api/cows/year/(?P<year>[0-9]{4})/$',
        CowListByYearView.as_view(),
        name='cow-list-year'),
    url(r'^api/cows/(?P<pk>\d+)/$',
        CowDetailView.as_view(),
        name='cow-detail'),
    url(r'^api/events/$',
        EventListView.as_view(),
        name='event-list'),
    url(r'^api/events/(?P<pk>\d+)/$',
        EventDetailView.as_view(),
        name='event-detail'),
    url(r'^api/exercises/$',
        ExerciseListView.as_view(),
        name='exercise-list'),
    url(r'^api/exercises/(?P<pk>\d+)/$',
        ExerciseDetailView.as_view(),
        name='exercise-detail'),
    url(r'^api/healthrecords/$',
        HealthRecordListView.as_view(),
        name='healthrecord-list'),
    url(r'^api/healthrecords/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$',
        HealthRecordListByMonthView.as_view(),
        name='healthrecord-list-month'),
    url(r'^api/healthrecords/illness/summary/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$',
        HealthRecordIllCowsSummaryView.as_view(),
        name='healthrecord-illness-summary-month'),
    url(r'^api/healthrecords/(?P<pk>\d+)/$',
        HealthRecordDetailView.as_view(),
        name='healthrecord-detail'),
    url(r'^api/milk/$',
        MilkListView.as_view(),
        name='milk-list'),
    url(r'^api/milk/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$',
        MilkListByMonthView.as_view(),
        name='milk-list-month'),
    url(r'^api/milk/summary/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$',
        MilkSummaryByMonthView.as_view(),
        name='milk-summary-month'),
    url(r'^api/milk/(?P<pk>\d+)/$',
        MilkDetailView.as_view(),
        name='milk-detail'),
    url(r'^api/pastures/$',
        PastureListView.as_view(),
        name='pasture-list'),
    url(r'^api/pastures/(?P<pk>\d+)/$',
        PastureDetailView.as_view(),
        name='pasture-detail'),
    url(r'^api/seeds/$',
        SeedListView.as_view(),
        name='seed-list'),
    url(r'^api/seeds/(?P<pk>\d+)/$',
        SeedDetailView.as_view(),
        name='seed-detail'),
]
